# Site
repository: shubhaminnani/shubhaminnani.github.io
favicon: images/favicon.ico

version: 2


# Personal info
name: Shubham Innani
title: Research Intern
email: shubham.innani@gmail.com
# email_title: Email (Email title override)
phone: +91 7023-999-795 / +1 215-397-7896
# phone_title: Phone (Phone title override)
website: shubhaminnani.github.io 
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: innani8
github_username:  shubhaminnani
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: innanishubham
linkedin_username: shubhaminnani
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
googlescholar_username: Aw0CjT8AAAAJ&hl

# Additional icon links
additional_links:
  - title: Link name
    icon: fa-solid fa-file-pdf
    url: https://github.com/shubhaminnani/shubhaminnani.github.io/blob/master/images/shubham_resume.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/1561796249984.jfif

about_content: |
  I'm Shubham and Research Intern at Center for Biomedical Image Comuting and Analytics (CBICA), University of Pennsylvania. 
  My Expertise include exploring Deep Learning Tools for Computer Vision Tasks such as Classification, Segmentation, Detection.  
  Currently working on H&E stained digital Histopathology Images for Prognostic Stratification of Glioblastoma.  
  I have worked with a range of different languages and frameworks and I am always looking for opportunities to work
  with something new. 
  The things that I currently have the most experience working with are:
  <mark>Deep Learning</mark>,
  <mark>Computer Vision</mark>,
  <mark>Medical Imaging</mark>,
  <mark>Tensorflow</mark>,
  <mark>Pytorch</mark>,
  <mark>Git</mark> and 
  <mark>Python</mark>.
#You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#    - Lists
 #   - Tables
 #   - <a href="google.com">Links</a>
 #   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Shri Guru Gobind Singhji Institute of Engineering and Technology, Nanded, Maharashtra, India
        sub_title: Bachelors of Technology - Electronics and Telecommunication Engineering
        caption: 2016 - 2020
        description: |
          During my degree at SGGSIE&T I learnt lots of key skills. 
          While at SGGSIE&T I spent a lot of my free time with Center of Excellence, Signal and Image Processing. 
          During this time, I learned concepts of Deep Learning and Computer Vision.

          

  - title: Projects & Publications # Title for the section
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Semantic Segmentation on India Driving Dataset (IDD) and IDD lite
        #link: 
       
           
        quote: >
          Semantic Segmentation in Unstructured Environment with Modified DeepLabV3+
          (AUTONUE Challenge, ICCV 2019 & NCVPRIPG Challenge 2019 & ICVGIP Challenge 2020)
        description: |
          Encoder-Decoder architecture is developed for semantic scene segmentation in unstructured environment with various 
          backbones like InceptionResNetV2, EfficientNets using Deep Learning on Indian Driving Dataset (IDD) and IDD lite.

          Baheti B, <mark>Innani S</mark>, Gajre S, Talbar S. <a href="https://ieeexplore.ieee.org/document/9150621">Eff-UNet: A Novel Architecture for Semantic Segmentation in Unstructured Environment.</a> 
          2020 IEEE CVF Conference on Computer Vision and Pattern Recognition Workshops (CVPRW), Seattle, WA, USA, 2020, pp. 1473-1481, doi: 10.1109/CVPRW50498.2020.00187.
      
          Bhakti Baheti, <mark>Shubham Innani</mark>, Suhas Gajre, Sanjay Talbar. 
          <a href="https://www.sciencedirect.com/science/article/abs/pii/S0167865520302750">Semantic scene segmentation in unstructured environment with modified DeepLabV3+.</a> 
          Elsevier Pattern Recognition Letters, Volume 138, 2020, Pages 223-229, ISSN 0167-8655,doi: 10.1016/j.patrec.2020.07.029.

      - layout: top-middle
        title: Age Related Macular Degeneration from Retinal Fundus Images.
        border: weak
       # link: 
        quote: >
          AMD Challenge, ISBI 2020
        description: |
          Development of algorithms associated with the diagnosis of Age-related Macular degeneration (AMD) and segmentation of lesions in fundus photos from AMD patients 
          with Convolutional Neural Networks.
          Fang H, Li F, Fu H, Sun X, Cao X, Lin F, Son J, Kim S, Quellec G, Matta S, Shankaranarayana SM, Ujjwal B, Shubham I and others, 
          <a href="https://ieeexplore.ieee.org/abstract/document/9768802">ADAM Challenge: Detecting Age-related Macular Degeneration from Fundus Images</a>, in IEEE Transactions on Medical Imaging, doi: 10.1109/TMI.2022.3172773.
          
          
      - layout: top-middle
        title: Anamoly Pattern Segmentation in Agriculture
        border: weak
        #link: www.itsgoingto.be
        additional_links:
          - title: sproogen/itsgoingto.be
            icon: fab fa-github
            url: https://github.com/sproogen/itsgoingto.be
        quote: >
          Anamoly Pattern Segmentation in Agriculture
        description: |
          Novel and effective algorithms is developed for agricultural pattern recognition from aerial images using Feature Pyramid Network as encoder and varying the decoder
          backbones.

          <mark>Innani, S. </mark>, Dutande, P., Baheti, B., Talbar, S., and Baid, U. <a href="https://ieeexplore.ieee.org/document/9150621"> 
          Fuse-PN: A Novel Architecture for Anomaly Pattern Segmentation in Aerial Agricultural Images.</a> 
          In Proceedings of the IEEE CVF Conference on Computer Vision and Pattern Recognition (CVPR) Workshops(2021)(pp. 2960-2968).


      - layout: top-middle
        title: Skin lesion Segmentation and Classification
        border: weak
        #link: www.itsgoingto.be
        additional_links:
          - title: sproogen/itsgoingto.be
            icon: fab fa-github
            url: https://github.com/sproogen/itsgoingto.be
        quote: >
          ISIC Challenge, MICCAI 2018
        description: |
          Generative Adversarial Network based architecture is developed for skin lesion segmentation and classification with Convolutional Neural Network. The classification 
          task is carried out with state-of-the-art networks like ResNets, MobileNets, Xception, EfficientNets.

          <mark>Innani, S. </mark>, Dutande, P., Baheti, B., Talbar, S., and Baid, U. 
          Deep Learning based Novel Cascaded Approach for Skin Lesion Analysis
          International Conference on Computer Vision and Image Processing, 2022 (In Press)




      - layout: top-middle
        title: Retinal Fundus Glaucoma Analysis
        border: weak
        #link: www.itsgoingto.be
        additional_links:
          - title: sproogen/itsgoingto.be
            icon: fab fa-github
            url: https://github.com/sproogen/itsgoingto.be
        quote: >
          REFUGE2 Challenge, MICCAI 2020
        description: |
          Algorithm for Retinal Fundus Glaucoma Analysis with segmentation of optic disc 
          and cup, classification of glaucoma and localization of fovea is being developed. We 
          leverage the power of Efficientnets and Unet for all the tasks.
          Fang H, Li F, Fu H, Sun X, Cao X, Son J, Yu S, Zhang M, Yuan C, Bian C, Lei B., Ujjwal B, Shubham I and others, 
          <a href="https://arxiv.org/abs/2202.08994"REFUGE2 Challenge: Treasure for Multi-Domain Learning in Glaucoma Assessment </a>. arXiv preprint arXiv:2202.08994. 2022 Feb 18. (Under review at Medical Image Analysis, Elsevier).


      - layout: top-middle
        title: Automatic Number Plate Recognition
        border: weak
        #link: www.itsgoingto.be
        additional_links:
          - title: sproogen/itsgoingto.be
            icon: fab fa-github
            url: https://github.com/sproogen/itsgoingto.be
        quote: >
          Anamoly Pattern Segmentation in Agriculture
        description: |
          Focus was on the development of novel and realtime algorithms for Automatic Number
          Plate Recognition. This algorithm implements end-to-end You Only Look Once (YOLO)
          based object detector and Mask-RCNN based Region Proposal Network.

      - layout: top-middle
        title: Prognostic Stratification of Glioblastoma
        #link: www.itsgoingto.be
        border: weak
        additional_links:
          - title: sproogen/itsgoingto.be
            icon: fab fa-github
            url: https://github.com/sproogen/itsgoingto.be
        quote: >
          Anamoly Pattern Segmentation in Agriculture
        description: |
          Focus is to develop computational algorithm from Digital H&E Stained Histopathology
          Images to derive the driving decision of Long and Short Survivals in Brain Tumor
          Patients using Weakly Supervised Approach.

  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Research Intern
        sub_title: CBICA
        caption: August 2022 - Present
        description: |
          Focus is to develop computational algorithm from Digital H&E Stained Histopathology 
          Images to derive the driving decision of Long and Short Survivals in Brain Tumor
          Patients using Weakly Supervised Approach. 
      - layout: left
        border: weak
        title: Assistant System Engineer
        sub_title: Tata Consultancy Services, Pune, India
        caption: January 2021 - July 2022
        description: |
          Worked with leading Bank as client for migration of legacy Infrastructure to AWS Cloud. 
          As an System Engineer job was to integrate various components with each other.
      - layout: left
        border: weak
        title: Nymo.ai
        sub_title: Data Science Intern
        #link: www.simitive.com
        caption: March 2022 - June 2022
        description: |
          During my time at Nymo.ai as Data Science Intern, worked to recognise the language of number plate for Automatic Number Plate Recognition System. 
          Also, worked on Mask Detection using YoloV3.

  - title: Awards and Accomplishment
    layout: list
    content:
      - layout: left
        border: weak
        sub_title: 2019
        description: |
          1st Prize in Semantic Segmentation Challenge on IDD lite dataset organized at National
          Conference on Computer Vision, Pattern Recognition, Image Processing and Graphics
          (NCVPRIPG),India, by IIIT Hyderabad, India and Intel, India.

      - layout: left
        border: weak
        sub_title: 2019
        description: |
          Travel Grant awarded to attend National Conference on Computer Vision, Pattern
          Recognition, Image Processing and Graphics (NCVPRIPG).


      - layout: left
        border: weak
        sub_title: 2019
        description: |
          Participated in AutoNUE Workshop Challenge organized at International Conference
          on Computer Vision (ICCV), Korea. 

      - layout: left
        border: weak
        sub_title: 2020
        description: |
          Poster Presentation at IEEE Conference on Computer Vision and Pattern Recognition
          (CVPR) in Agriculture Vision Workshop.

      - layout: left
        border: weak
        sub_title: 2020
        description: |
          Participated in Agriculture Vision Prize Challenge at Computer Vision and Pattern
          Recognition (CVPR).

      - layout: left
        border: weak
        sub_title: 2020
        description: |
          Participated in Age Related Macular Degeneration(AMD) challenge at IEEE International Symposium on Biomedical Imaging (ISBI) and ranked in top 10.
      
      - layout: left
        border: weak
        sub_title: 2020
        description: |
          Participated in Retinal Fundus Glaucoma Challenge Edition2 (REFUGE2) challenge at MICCAI, ranked in top 10.
      
      - layout: left
        border: weak
        sub_title: 2020
        description: |
          2nd Prize in Semantic Segmentation Challenge on IDD dataset organized at Indian
          Conference on Computer Vision, Graphics and Image Processing (ICVGIP) at IIT
          Jodhpur, by IIIT Hyderabad, and Intel, India.


  # - title: Knowledge Area
  #   layout: list
  #   content:
  #     - layout: left
  #       border: weak
  #       title: Networks
  #       #sub_title: 
  #       #caption: July 2021 - Present
  #       description: |
  #         Convolutional Neural Network (CNN), Segmentation Models, CNN based classification
  #         models, Object detection models, Generative Adversarial Networks (GAN)
  #     - layout: left
  #       border: weak
  #       title: Libraries
  #       sub_title: Tata Consultancy Services, Pune, India
  #       caption: August 2017 - July 2021
  #       description: |
  #         Worked with leading Bank as client for migration of legacy Infrastructure to AWS Cloud. 
  #         As an System Engineer job was to integrate various components with each other.
  #     - layout: left
  #       border: weak
  #       title: Nymo.ai
  #       sub_title: Data Science Intern
  #       #link: www.simitive.com
  #       caption: November 2015 - August 2017
  #       description: |
  #         During my time at Nymo.ai as Data Science Intern, worked to recognise the language of number plate for Automatic Number Plate Recognition System. 
  #         Also, worked on Mask Detection using YoloV3.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I aim to work in an organization with research-based opportunities where I can utilize 
      my skills to achieve the organizationâ€™s objective and grow personally and professionally.
      Despite the short period of experience in the research sector, I have interest willingness to learn new things.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed